### ISSUE TITLE
relevant notebook

### ISSUE THREAD

**Issue by emilkone** [ErikFantomex/Segmentacion_Angiogramas#5]
Hello, can I get the result like in the screenshots? Or is it special results for the article?
And which notebook is relevant?

**Comment by ErikFantomex** [comment]
For the result of the image you need the matlab version of the Gaussian matched filter is there in the repo

**Comment by ErikFantomex** [comment]
i will upload that version in this repo

**Comment by ErikFantomex** [comment]
also you need to implement conected components and Randolph douglas peucker algorithm

**Comment by ErikFantomex** [comment]
Check the secondary branch in this repo

**Comment by ErikFantomex** [comment]
follow this link it will answer the question of what notebook is relevant 
https://github.com/ErikFantomex/Segmentador_Angiogramas

**Comment by emilkone** [comment]
Thanks for this. I began to understand a little.
But I don't understand where UMDAc is used
